### ISSUE TITLE
Gno Core Issue Tracker

### ISSUE THREAD

**Issue by dongwon8247** [gnoswap-labs/gno#7]
# Description
This issue tracker contains a list of things that Onbloc and Gnoswap need from the Gnoland Core side. Its purpose is to centralize all the issues in one place for better coordination and management.

## Major Features

 - [x] 1. Inter contract interaction [#757](https://github.com/gnolang/gno/issues/757)
   - Usecase: Dapps that need to manage GRC20 & GRC721 tokens dynamically (i.g. DeFi dapp)
   - Related to:
		- https://github.com/gnolang/gno/pull/952
		- https://github.com/gnolang/gno/pull/473
	- Completed in:
		- https://github.com/gnolang/gno/pull/1262
		- https://github.com/gnolang/gno/pull/1275

- [x] 2. Emit & event function with WS & subscribe support [#575](https://github.com/gnolang/gno/issues/575) (like `eth_subscribe`, `eth_unsubscribe` in Ethereum)
	- Usecase: To subscribe block/transaction events from TM2 for an indexer, and realms for ongoing events
	- Related to: 
		- https://github.com/gnolang/gno/pull/546	
		- https://github.com/gnolang/gno/pull/853

- [x] 3. Porting Go packages to pure Gno [stdlibs](https://github.com/gnolang/gno/blob/master/gnovm/docs/go-gno-compatibility.md#stdlibs), [#33](https://github.com/gnolang/roadmap/issues/33), [1267](https://github.com/gnolang/gno/issues/1267) 
	- Usecase: Porting essential Go packages such as `bigint`, `bytes`, `reflect`, `encoding`, `json` parser, `testing`, and `io`
	- Completed in:
		- [x] Add `bigint` https://github.com/gnolang/gno/pull/764
		- [x] Replace `io/ioutil` to `os` https://github.com/gnolang/gno/pull/1277
		- [x] Add `hash` https://github.com/gnolang/gno/pull/1273
		- [x] Add `encoding` https://github.com/gnolang/gno/pull/1290
		- [x] Add `io/fs` https://github.com/gnolang/gno/pull/1323
		- [x] Add `json` parser https://github.com/gnolang/gno/pull/1415
		- [x] Add `u/int256` https://github.com/gnolang/gno/pull/1778 https://github.com/gnolang/gno/pull/1848
		- [x] Add `unicode/utf16` https://github.com/gnolang/gno/pull/1764
		- [x] Adding more packages https://github.com/gnolang/gno/pull/1809 

- [x] 4. Lead Multi-node Testnet Initiative [#9](https://github.com/gnolang/hackerspace/issues/9), [#863](https://github.com/gnolang/gno/issues/863)
	- Usecase: Lead multi-node testnet initiative on a separate testnet with community validators
	- Related to: 
		- https://github.com/gnolang/gno/pull/871
		- https://github.com/gnolang/gno/pull/889

### Not required for Mainnet

- [ ] 5. Upgradable Realms [#694](https://github.com/gnolang/gno/issues/694)
	- Usecase: Proxy pattern and storage migration for realms
	- Related to: *(Not being addressed at the moment)*

## Minor Bugs

 - [x] 1. Block data sync-related issues [#863](https://github.com/gnolang/gno/issues/863)
	 - Usecase: Operating the full node (For teams/individuals that need an indexer)
	 - Related to: #899
- [ ] 2. Support skipping timestamp in test case https://github.com/gnolang/gno/pull/569
	- Usecase: To test logic that depends on how much time has been passed
- [x] 3. PrevRealm testing bug fix [#891](https://github.com/gnolang/gno/pull/891)
	- Usecase: To fix a problem of having different results in `gno test` and `gnoland & gnokey`
	- Related to: https://github.com/gnolang/gno/pull/896
- [x] 4. Change the banker module [#875](https://github.com/gnolang/gno/pull/875)
	- Usecase: To fix a bug of minting additional coins using `banker`.
	- Related to: https://github.com/gnolang/gno/pull/875 https://github.com/gnolang/gno/pull/393 
- You can find more bug fixes here: https://github.com/orgs/gnolang/projects/23/views/1

**Comment by r3v4s** [comment]
~~6. Support skipping timestamp in test cases. #569~~
~~- Usecase: testing logics that depends on how much time have been passed~~
~~- Depends on: nothing at this moment~~

Merged with the main comment for better visibility

**Comment by r3v4s** [comment]
~~7. PrevRealm~~ 
~~- related: https://github.com/gnolang/gno/pull/896~~
~~- issue: result is different from `gno test` and `gnoland & gnokey`~~
~~- **can be by pass with, https://github.com/gnolang/gno/pull/891**~~

Merged with the main comment for better visibility

**Comment by r3v4s** [comment]
~~8. Upgradable Contract~~
~~- proxy pattern~~
~~- storage migration~~ 

Merged with the main comment for better visibility

**Comment by r3v4s** [comment]
## Details of the Contract Interaction Issue

### 1. When importing token realms

Current: Import tokens manually (https://github.com/gnoswap-labs/gnoswap/blob/d624686b1d3af19313ab407ac3d626ec87e6c68d/pool/pool_manager.gno#L7-L8)
```go
import (
  "std"
  "strconv"
  
  foo "gno.land/r/foo" // Import token0 manually
  bar "gno.land/r/bar" // Import token1 manually
  
  "gno.land/p/demo/ufmt"
)
```
Ideally with contract interaction functionality:
```
no need to import each token
```

### 2. When creating a pool

Current: Set token0 as `foo`, and token1 as `bar` manually, which are imported from above (https://github.com/gnoswap-labs/gnoswap/blob/d624686b1d3af19313ab407ac3d626ec87e6c68d/pool/pool_manager.gno#L119-L135)

```go
return &Pool{
  token0:               foo.GetGRC20(),
  token1:               bar.GetGRC20(),
  balances:             balances,
  fee:                  fee,
  tickSpacing:          tickSpacing,
  maxLiquidityPerTick:  maxLiquidityPerTick,
  slot0:                slot0,
  feeGrowthGlobal0X128: 0,
  feeGrowthGlobal1X128: 0,
  protocolFees:         protocolFees,
  liquidity:            0,
  ticks:                Ticks{},
  tickBitmaps:          TickBitmaps{},
  positions:            Positions{},
}
```

Ideally with contract interaction functionality:
```go
return &Pool{
  token0:               std.Call("gno.land/r/foo", GetGRC20) // Example with std.Call
  token1:               std.Call("gno.land/r/bar", GetGRC20) // Example with std.Call
  balances:             balances,
  fee:                  fee,
  tickSpacing:          tickSpacing,
  maxLiquidityPerTick:  maxLiquidityPerTick,
  slot0:                slot0,
  feeGrowthGlobal0X128: 0,
  feeGrowthGlobal1X128: 0,
  protocolFees:         protocolFees,
  liquidity:            0,
  ticks:                Ticks{},
  tickBitmaps:          TickBitmaps{},
  positions:            Positions{},
}
```


### 3. When swapping tokens

Current: Same as creating a pool, we have to set token0 as `foo`, and token1 as `bar` manually, which are imported from above ([swap token0](https://github.com/gnoswap-labs/gnoswap/blob/d624686b1d3af19313ab407ac3d626ec87e6c68d/pool/pool.gno#L391-L399) & [swap token1](https://github.com/gnoswap-labs/gnoswap/blob/d624686b1d3af19313ab407ac3d626ec87e6c68d/pool/pool.gno#L383-L388))

```go
if amount1 < 0 {
  // handle token1
  bar.Transfer(a2u(recipient), uint64(-1*amount1))
}

// handle token0
from := a2u(GetOrigCaller()) // token should be transferred from actual user(GetOrigCaller), not from the realm(PrevRealm)
to := a2u(GetOrigPkgAddr())

foo.TransferFrom(from, to, uint64(amount0))
```

Ideally with contract interaction functionality:
```go
if amount1 < 0 {
  // handle token1
  pool.token1.Transfer(a2u(recipient), uint64(-1*amount1))
}

// handle token0
from := a2u(GetOrigCaller()) // token should be transferred from actual user(GetOrigCaller), not from the realm(PrevRealm)
to := a2u(GetOrigPkgAddr())

pool.token0.TransferFrom(from, to, uint64(amount0))
```
-----

## Problems
- We have to import all of the existing token realms manually before creating a pool, and supporting a swap
- We can't support token realms that didn't exist when deploying the pool contract
	- If we're to support new token realms after the pool contract deployment, then we have to manually import it in a new pool contract and re-deploy it, which causes a path conflict issue, and contract upgradability issue (storage migration) 

## What Inter-contract Functionality Unlocks
- We can remove all of the hard-coded values (`foo`, `bar`) and call a contract's functions without manually importing it, just like EVM's `abi.Call`.
	- We can set `token pkg_path` value into the pool structure and dynamically call the function using `token pkg_path`
- We can support new token realms for creating a pool and swapping without re-deploying the pool contract

## Moving Forward
- Based on @moul's work [#938](https://github.com/gnolang/gno/pull/938), [#952](https://github.com/gnolang/gno/pull/952), and @jaekwon's [comment](https://github.com/gnolang/gno/pull/938#issuecomment-1631835458) on the inter contract call issue, having `banker20` in the GRC20 spec to support GRC20 tokens to be used dynamically would be the way to resolve the inter contract issue.
- We will study more on the issue based on Manfred's ongoing work [#952](https://github.com/gnolang/gno/pull/952), and try to come up with suggestions next time.
- Any advice on the direction to move this forward would be appreciated.

**Comment by moul** [comment]
For contract-contract interaction without modifying the gnovm (without adding `std.Call` or IBC), I propose the following plans:

**Option 1:** Create a main contract, let's call it `r/gnoswap/hub`, which includes a `RegisterSwapper` function. This function can be called from new contracts that you add later, such as `r/gnoswap/swapper-foo20`. During the `init()` phase, the new contracts can register themselves on the hub like this: `hub.RegisterSwapper("foo20", mySwapper)`, where `mySwapper` is a global variable implementing the `hub.Swapper` interface. Subsequently, the hub can utilize its local registry of tokens and call swapper methods without needing to import them.

Edit: https://github.com/gnolang/gno/pull/1262

**Option 2:** Consider code generation to register new contracts for each token or potentially for each token-pair. Your frontend would need to be aware of which contract to call depending on the scenario. These contracts could import a `hub/keeper` to attempt centralizing the GRC20s in a semi-permissionless manner. The goal of the `hub/keeper` is to provide a central address for both native tokens and GRC20s (you can use the `Approve` method to delegate GRC20 management to your keeper).
